name: Build

on:
  workflow_call:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  PackageOutputPath: ${{ github.workspace }}/packages

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release --property:PackageOutputPath=${{ env.PackageOutputPath }}

    - name: Upload artifacts
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: packages
        path: ${{ env.PackageOutputPath }}/*.nupkg
