name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+", "v[0-9]+.[0-9]+.[0-9]+-*" ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  nuget-push:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: packages
          path: ./packages
      
      - name: Publish
        run: dotnet nuget push "./packages/*.nupkg" --no-symbols --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_KEY }}
